from __future__ import annotations

import hashlib
import hmac
from xhh_sdk.web_signer import (
    calc_hkey,
    calc_rnd,
    generate_nonce,
    sign_web_request,
    RND_KEY,
)


def test_calc_hkey_deterministic():
    """Verify web hkey matches the decompiled Creator SPA Ow.g logic."""
    path = "/bbs/app/api/link/post"
    timestamp = 1700000000
    nonce = "3oCpwCioQCL3CXRW4SIKai3abwXba6Ci"
    hkey = calc_hkey(path, timestamp, nonce)
    assert hkey == "1IX7W55"


def test_calc_rnd_hmac():
    """Verify _rnd matches HMAC-SHA256 with RND_KEY and prefix '15:'."""
    timestamp = 1700000000
    nonce = "3oCpwCioQCL3CXRW4SIKai3abwXba6Ci"
    rnd = calc_rnd(nonce, timestamp)
    assert rnd.startswith("15:")
    expected_sig = hmac.new(
        RND_KEY.encode("utf-8"),
        (RND_KEY + nonce + f"{timestamp}:{nonce}").encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    assert rnd == "15:" + expected_sig
    assert rnd == "15:9f00109105627ebc49beefe3c937996a3af27c7f8d79925b3103eb0b3caabc54"


def test_sign_web_request_quadruple():
    """Verify complete quadruple generated by pure web signer."""
    path = "/bbs/app/link/drafts"
    timestamp = 1700000000
    nonce = "fixed_test_nonce_32_chars_12345"
    res = sign_web_request(path, timestamp=timestamp, nonce=nonce)
    assert res["_time"] == str(timestamp)
    assert res["nonce"] == nonce
    assert res["version"] == "999.0.4"
    assert res["_rnd"].startswith("15:")
    assert isinstance(res["hkey"], str) and len(res["hkey"]) >= 5


def test_generate_nonce():
    nonce = generate_nonce(32)
    assert len(nonce) == 32
    assert nonce.isalnum()


def test_matches_current_official_creator_qr_request():
    # Captured from the unauthenticated Creator page, not computed by this module.
    assert calc_hkey("/account/get_qrcode_url/", 1791521842,
                     "DB8003B5757537F011FE6B4E71C42262") == "X27YI27"
